apiVersion: v1
data:
  prometheus.yml: |+
    ###
    #
    # Copyright 2017-2022 Crunchy Data Solutions, Inc. All Rights Reserved.
    #
    ###

    ---
    global:
      scrape_interval: 15s
      scrape_timeout: 15s
      evaluation_interval: 5s


    rule_files:
      - /etc/prometheus/alert-rules.d/*.yml
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "crunchy-alertmanager:9093"

kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: postgres-operator-monitoring
    vendor: crunchydata
  name: crunchy-prometheus
